# SPDX-FileCopyrightText: (c) 2025 Jeff C. Jensen
# SPDX-License-Identifier: MIT
---
- name: Download Spotify GPG key
  become: true
  ansible.builtin.get_url:
    url: https://download.spotify.com/debian/pubkey_5384CE82BA52C83A.asc
    dest: /usr/share/keyrings/spotify.gpg
    mode: u=rw,g=r,o=r

- name: Dearmor Spotify GPG key
  become: true
  ansible.builtin.shell: >
    gpg --dearmor
    --output /etc/apt/keyrings/spotify.gpg
    /usr/share/keyrings/spotify.gpg
  args:
    creates: /etc/apt/keyrings/spotify.gpg

- name: Configure Spotify APT repository
  register: _spotify_repo
  become: true
  ansible.builtin.deb822_repository:
    name: spotify
    types: [deb]
    uris: https://repository.spotify.com
    suites: [stable]
    components: [non-free]
    signed_by: /etc/apt/keyrings/spotify.gpg
    enabled: true
    state: present

- name: Update APT cache
  become: true
  ansible.builtin.apt:
    update_cache: "{{ _spotify_repo.changed }}"

- name: Install Spotify
  become: true
  ansible.builtin.apt:
    name: spotify-client
